#!/bin/bash
curl -sSLf https://get.k0s.sh | sudo sh
sudo k0s install controller --single
sudo k0s install controller -e ETCD_UNSUPPORTED_ARCH=arm
sudo k0s install controller --single --force
sudo systemctl daemon-reload
k0s version
